name: Maven 

on:
  workflow_call:
    inputs:
      maven-goal:
        description: 'Maven goal to run'
        required: true
        default: 'package'
        type: string
  
permissions:
  contents: read

jobs:
    build:
      name: build
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v4
         with:
          path: ${{ github.repository }}
          fetch-depth: 0
       - uses: whelk-io/maven-settings-xml-action@v22
         with:
          servers: '[{ "id":"github-vol-active-support", "configuration": { "httpHeaders": { "property": { "name":"Authorization", "value":"Bearer ${{ secrets.GITHUB_TOKEN }}"} } } } ]'
      
       - run: mvn -B -P github ${{ inputs.maven-goal}}
    