name: Maven Build

on:
  workflow_call:
  
permissions:
  contents: read

jobs:
    build:
      name: build
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-java@v4
         with:
            distribution: "corretto"
            java-version: "8"
            cache: maven  
       - uses: whelk-io/maven-settings-xml-action@v22
         with:
            servers: '[{ "id":"github-vol-active-support", "configuration": { "httpHeaders": { "property": { "name":"Authorization", "value":"Bearer ${{ secrets.GITHUB_TOKEN }}"} } } } ]'
       - run: mvn -B -P github package

    